### ISSUE TITLE
[BUG] Mod filter does not match spaces

### ISSUE THREAD

**Issue by krissrex** [scottbot95/RoR2ModManager#107]
**Describe the bug**
Filtering mods (searching) will not match if the filter has spaces in it.

**To Reproduce**
1. Go to `Select packages`
2. Type in `Ro R2` in `Filter` textbox
3. No matches for `R2 Ro Mod Manager` is shown

**Expected behavior**
The results should include at least `Ro R2 Mod Manager` and other results with spaces in their names.

**Screenshots**
![image](https://user-images.githubusercontent.com/7364831/60210202-9ffbc000-985c-11e9-896e-9c3975879ea1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 1.0.0
![image](https://user-images.githubusercontent.com/7364831/60210240-b6a21700-985c-11e9-9f5f-d73f60ff29a9.png)

**Comment by krissrex** [comment]
I think the reason is that [package-table-datasource.ts](https://github.com/scottbot95/RoR2ModManager/blob/master/src/app/main/package-selection/package-table/package-table-datasource.ts) is not searching in the [humanized](https://github.com/scottbot95/RoR2ModManager/blob/master/src/app/shared/humanize.pipe.ts) version of [the package table](https://github.com/scottbot95/RoR2ModManager/blob/2848417e59988fd2e16a679108ca1d91de033c11/src/app/main/package-selection/package-table/package-table.component.html#L121).

**Comment by scottbot95** [comment]
Yeah that's almost certainly the issue. I'm out of town until the 8th. I can take a crack at it then.
