### ISSUE TITLE
Cant change profile in Preferences menu

### ISSUE THREAD

**Issue by wavewarrior** [scottbot95/RoR2ModManager#108]
My friend is too stubborn, to admit that any functionality regarding installing mods should happen in the packages tab. Could you please add in the functionality to send the user back to the packages list upon selecting a different profile, regardless of which menu the user is currently in

**Comment by scottbot95** [comment]
Yeah that's a totally reasonable request and one that should be pretty easy. I'm on vacation right now but when I get back I can take a look a implementing that.
