### ISSUE TITLE
Changing profiles clears packages

### ISSUE THREAD

**Issue by Sparxta11** [scottbot95/RoR2ModManager#110]
Changing to another profile clears the selected packages for the new profile, as if the profiles do not save which packages are selected or 'forget' when swapped.

**Comment by scottbot95** [comment]
Sorry for delayed response, I've been out of town. By clearing the selected packages, do you mean the packages that were installed already? Or just the packages you had selected, but not installed yet? It should be saving to the profile whenever it installs packages.

If you want, you can hit `ctrl+shift+i` to pop open the dev tools, click on the 'Application' tab at the top ( you may have to use the arrow to view more tabs), find 'IndexedDb' on the left and dive into that until you see the 'profiles' database. That should list all the packages and versions the mod manager thinks should be installed for each profile.
