### ISSUE TITLE
[BUG] Installer is scuffed

### ISSUE THREAD

**Issue by xiaoxiao921** [scottbot95/RoR2ModManager#111]
The default path lacks a space between Files and (x86) for some reason.

**Comment by xiaoxiao921** [comment]
https://github.com/scottbot95/RoR2ModManager/blob/e31c282be360236b640197081fd45878b2821223/build/installer.nsh#L15

**Comment by scottbot95** [comment]
Not sure how this has gone unnoticed for so long lol. Good catch
