### ISSUE TITLE
[BUG] R2Api not installing correctly

### ISSUE THREAD

**Issue by scottbot95** [scottbot95/RoR2ModManager#113]
**Describe the bug**
The R2API isn't getting installed correctly. Specifically, it seems the monomod patch isn't getting applied.

**To Reproduce**
1. Remove all mods from install
2. Attempt to install R2API
3. Mod Manager says install successes, but monomod patch is missing

It appears to be failing to move the extracted file from the temp folder to the managed folder, I suspect this is an issue with the zip extract process.

**Comment by GalacticRuler** [comment]
Bug Persists in 1.0.3.

Also missing 2 files for BepInEx (doorstop_config.ini and winhttp.dll)
