### ISSUE TITLE
[BUG] Can't load packages

### ISSUE THREAD

**Issue by PlayerTw0** [scottbot95/RoR2ModManager#115]
**Describe the bug**
Upon opening the Mod Manager, the packages fail to load, show an infinite spinning circle. 

**To Reproduce**

**Expected behavior**
Packages to load in after opening. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.2

**Additional context**
MM worked fine one day, and wouldn't load packages the next. Thunderstore is not the issue, as it was up at the time. Uninstalling and reinstalling didn't fix the issue. Trying to import a profile leads to an error "packages not loaded".

**Comment by scottbot95** [comment]
Turns out someone uploaded a mod that with a dependency that they didn't also upload and the mod manager really didn't like that. Fix coming shortly
