### ISSUE TITLE
Mods don't download

### ISSUE THREAD

**Issue by Pysis868** [scottbot95/RoR2ModManager#40]
Waited long enough without having a progress bar, noticed the plugins folder still doesn't have any mods that I selected downloaded.
Sorted mods list by downloads descending, selected a few and hit Apply.

0.3.1
Win 10

My RoR2 is not in a Steam library in a special folder like Program Files.

**Comment by scottbot95** [comment]
I'm currently working on a rework of the download system. Hopefully when I'm done it will fix this is all. If not, i'll look into it

**Comment by Pysis868** [comment]
I woke up my computer, opened the application again, followed the same steps for 1 and the increasing mods.  They download now.  Install path is the same.  This program is in Program Files still.  I was not able to bring up any developer console during this process.
