### ISSUE TITLE
Install not setting RoR2 install Path

### ISSUE THREAD

**Issue by scottbot95** [scottbot95/RoR2ModManager#68]
It seems under certain circumstances the `ror2_path` preference doesn't get set properly which causes installs to default to the mod manager install directory.

I suspect this occurs when the user didn't change the install path in the installer.

**Comment by dmratcliffe** [comment]
https://github.com/scottbot95/RoR2ModManager/issues/56#issuecomment-490681076
(I figured responding here was more on topic)"
>I'm curious, did you install RoR2 in the default location? I suspect it might have something to do with >that. Also what version of the installer did you use?

RoR2 is not installed in the default location per se, its on a second steam drive and it detected the folder properly in the installer iirc.

The one most recent in releases.

**Comment by dmratcliffe** [comment]
Also, I DID change the path in the installer, it was set to the default game dir, I wanted it in one with a "- mods" after it

**Comment by scottbot95** [comment]
I think I found the problem. The installer was saving the input directory to a different registry hive than the app was reading it back from. Should be a quick fix
