### ISSUE TITLE
[BUG] Config Editor Page Stuck on Loading

### ISSUE THREAD

**Issue by dastrdly6585** [scottbot95/RoR2ModManager#71]
**Describe the bug**
The config editor page is stuck perpetually loading (with spinning circle) unless you temporarily switch window focus or a keyboard button is pressed, at which point the config files immediately load in.  This occurs every time you access the config editor from a different menu entry.

**To Reproduce**
1. Go to 'Config Editor' under Menu
2. Loading icon never disappears
3. Click out of mod manager window and click back in (or hit any keyboard button while in the manager window)
4. Config files immediately load

**Expected behavior**
Config editor should instantly show available config files to edit once they're loaded and not require the mod manager to lose focus before displaying them.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.6.2

**Comment by scottbot95** [comment]
Turned out to be an easy fix actually. I'm pushing a patch later today that should this and some other bugs.
