### ISSUE TITLE
[BUG]Dependency fails to install.

### ISSUE THREAD

**Issue by Cylek358** [scottbot95/RoR2ModManager#88]
When choosing to install a mod with more than Bepinex as a dependency, the dependency doesn't get set for download but shows as auto selected in the gui.
**To Reproduce**
With a fresh install, attempt to install Engineer Lunar Coins Fix, which has ToyDragons frogtown shared library as a dependency.
After applying, check the folder in the directory.  You could also launch the game and check the bep log for more info.

**Comment by scottbot95** [comment]
I tried to reproduce this, but unfortunately it properly installed the dependency mods on my computer.

A couple questions:

1. What version of the mod manager do you have installed? (most recent is 0.7.0 as of the the time I wrote this)
2. Does the confirm page show the proper changes to be applied?
3. Assuming you can reproduce this on your own, are there any errors printed in the console? (accessible by `ctrl+shift+i`)

**Comment by Cylek358** [comment]
no errors, just didn't load engineerlunarcoinfix when launched.
On 0.7.0
confirm page shows installing the engineerlunarcoinfix but not toydragon shared.

**Comment by Cylek358** [comment]
ok, just tried to reproduce, and failed to do so.  Must have been a fluke, sorry.

**Comment by scottbot95** [comment]
Huh. Well if it ever happens again, check the console.

I am currently doing some re-working to how packages get marked for change so it may just fix itself.
