### ISSUE TITLE
[FEATURE] Install specific version of mod

### ISSUE THREAD

**Issue by nickrenfo2** [scottbot95/RoR2ModManager#90]
Recently, the "Sacrifice" mod has been updated, and no longer works with BepInEx v1.3.1. However, an older version of the Sacrifice package still works just fine.

It would be nice to be able to select a specific version to install, from the list of versions in the "info" section that shows when you click on a package.

![RoR2MM](https://user-images.githubusercontent.com/8879489/58059073-975eee00-7b28-11e9-8ae0-b4f537b2f89c.PNG)

**Comment by scottbot95** [comment]
For now, you should be able to use profiles to install a specific version of a mod.

 I plan to have 1.0 out by the end of this week, I should be able to get this included in that release.
